Shop_MVC/Controllers/BasketController.cs
using Microsoft.AspNetCore.Mvc;
using Shop_MVC.Models.Basket;
using Shop_MVC.Models.Products;
using Shop_MVC.Services;
using Shop_MVC.Services.Interfaces;

namespace Shop_MVC.Controllers
{
    public class BasketController : Controller
    {
        private readonly IBasketService basketService;
        private readonly IOrderService orderService;
        public BasketController(IBasketService basketService, IOrderService orderService)
        {
            this.basketService = basketService;
            this.orderService = orderService;
        }
        public IActionResult Index()
        {
            return View(new BasketViewModel() { Products = [] });
        }

        [HttpPost]
        public IActionResult GetBasket([FromBody] IEnumerable<BasketProductLocalStorage> basketProducts)
        {
            var basket = basketService.GetBasket(basketProducts);
            return PartialView("Index", basket);
        }

        [HttpPost]
        public IActionResult Buy([FromBody] IEnumerable<BasketProductLocalStorage> basketProducts)
        {
            bool result = false;

            try
            {
                result = orderService.Buy(basketProducts);
            }
            catch (Exception ex)
            {
                return Json(new
                {
                    success = false,
                    message = ex.Message,
                    type = "danger"
                });
            }

            if (result)
            {
                return Json(new
                {
                    success = true,
                    message = "Purchase Completed",
                    type = "success"
                });
            }

            return Json(new
            {
                success = false,
                message = "Something went wrong",
                type = "danger"
            });
        }
    }
}

Shop_MVC/Controllers/ProductsController.cs
using Microsoft.AspNetCore.Mvc;
using MongoDB.Bson;
using Shop_MVC.Entities.Enums;
using Shop_MVC.Models.Products;
using Shop_MVC.Services;
using Shop_MVC.Services.Interfaces;

namespace Shop_MVC.Controllers
{
    public class ProductsController : Controller
    {
        private readonly IProductService productService;
        public ProductsController(IProductService productService)
        {
            this.productService = productService;
        }

        public IActionResult Index()
        {
            var categories = Enum.GetValues(typeof(Category)).Cast<Category>();
            var companies = Enum.GetValues(typeof(Company)).Cast<Company>();
            var colors = Enum.GetValues(typeof(Color)).Cast<Color>();

            var model = new ProductsViewModel
            {
                Products = productService.GetProducts(),
                Categories = categories,
                Companies = companies,
                Colors = colors
            };

            return View(model);
        }

        [HttpPost]
        public IActionResult Filter([FromBody] ProductsFilter filter)
        {
            var filteredProducts = productService.GetFilteredProducts(filter);
            return PartialView("_ProductsPartial", filteredProducts);
        }

        [Route("Products/Details/{Id}")]
        public IActionResult Details(string Id)
        {
            try
            {
                var model = productService.GetProductsWithComments(Id);
                return View(model);
            }
            catch (KeyNotFoundException ex)
            {
                return NotFound(ex.Message);
            }
            catch (Exception ex)
            {
                return StatusCode(500, ex.Message);
            }
        }
    }
}

Shop_MVC/Controllers/UserManagerController.cs
using Microsoft.AspNetCore.Mvc;
using MongoDB.Bson;
using Shop_MVC.Models.UserManager;
using Shop_MVC.Services.Interfaces;

namespace Shop_MVC.Controllers
{
    public class UserManagerController: Controller
    {
        private readonly IUserManagerService userMngService;
        public UserManagerController(IUserManagerService userManagerService)
        {
            userMngService = userManagerService;
        }
        public IActionResult Index()
        {
            var model = userMngService.GetUsers();
            return View(model);
        }

        public IActionResult AddMoney(string email)
        {
            var user = userMngService.GetByEmail(email);
            if (user == null)
            {
                return RedirectToAction(nameof(Index));
            }
            return View(user);
        }

        [HttpPost]
        public IActionResult AddMoney(UserManagerViewModel user)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    userMngService.AddMoney(user);
                    return RedirectToAction(nameof(Index));
                }

                return View(user);
            }
            catch (Exception ex)
            {
                TempData["ToastMessage"] = ex.Message;
                TempData["ToastType"] = "Error";
                return View(user);
            }
        }
    }
}

Shop_MVC/Views/Shared/_Layout.cshtml
@using System.Security.Claims
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Shop_MVC</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/products.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/basket.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Shop_MVC.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css">
</head>
<body>
    <header>
        <nav class="navbar fixed-top navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid justify-content-start">
                <a class="navbar-brand" asp-area="" asp-controller="Products" asp-action="Index">Shop_MVC</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="d-flex justify-content-between w-100">
                    <div>
                        <ul class="navbar-nav">
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Products" asp-action="Index">Products</a>
                            </li>
                            @if (User.Identity?.IsAuthenticated == true)
                            {
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="Basket" asp-action="Index">Basket</a>
                                </li>
                            }
                            @* Zakładka dostępna tylko dla zalogowanego użytkownika w roli: Administrator *@
                            @{
                                bool isAuthenticated = User.Identity?.IsAuthenticated == true;
                                var roleClaim = User.Claims.FirstOrDefault(c => c.Type == ClaimTypes.Role);
                                bool isAdmin = roleClaim != null ? roleClaim.Value == "Admin" : false;
                            }
                            @if (isAuthenticated && isAdmin)
                            {
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="UserManager" asp-action="Index">User Manager</a>
                                </li>
                            }
                        </ul>
                    </div>
                    <div>
                        <ul class="navbar-nav">
                            @if (User.Identity?.IsAuthenticated == true)
                            {
                                <li class="nav-item">
                                    <span id="user_identity_name_span" class="nav-link text-primary">Hello, @User.Identity.Name!</span>
                                </li>
                                <li class="nav-item" id="balance-container">
                                    <span class="nav-link text-primary">Balance: <span id="user-balance">loading...</span> $</span>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-controller="Account" asp-action="Logout">Logout</a>
                                </li>
                            }
                            else
                            {
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-controller="Account" asp-action="Register">Register</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-controller="Account" asp-action="Login">Login</a>
                                </li>
                            }
                        </ul>
                    </div>
                </div>
            </div>
        </nav>
    </header>
    <div>
        <div class="main">
            @RenderBody()
        </div>
    </div>

    <!-- Toast Notifies -->
    <!-- dynamic -->
    <div aria-live="polite" aria-atomic="true" class="position-relative">
        <div id="toastContainer" class="toast-container position-fixed bottom-0 end-0 p-3"></div>
    </div>

    <!-- static -->
    <div aria-live="polite" aria-atomic="true" class="position-relative">
        <div class="toast-container position-fixed bottom-0 end-0 p-3">
            @if (TempData["ToastMessage"] != null)
            {
                var toastType = TempData["ToastType"] ?? "info";
                <div class="toast text-white bg-@toastType border-0 show"
                     role="alert"
                     data-bs-autohide="true"
                     data-bs-delay="5000">
                    <div class="d-flex">
                        <div class="toast-body">
                            @TempData["ToastMessage"]
                        </div>
                        <button type="button" class="btn-close btn-close-white me-2 m-auto" data-bs-dismiss="toast"></button>
                    </div>
                </div>
            }
        </div>
    </div>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="~/js/account.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>